---
- name: Install node-related packages
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm

- name: Create user {{ uptime_kuma_user }}
  ansible.builtin.user:
    name: "{{ uptime_kuma_user }}"
    home: "{{ uptime_kuma_home }}"
    create_home: true
    system: true
    shell: /usr/sbin/nologin

- name: Create datadir
  ansible.builtin.file:
    path: "{{ uptime_kuma_data_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ uptime_kuma_user }}"
    group: "{{ uptime_kuma_user }}"
