---
- name: Create systemd service unit
  ansible.builtin.template:
    src: uptime-kuma.service.j2
    dest: /etc/systemd/system/uptime-kuma.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart uptime-kuma

- name: Enable and start uptime-kuma systemd unit
  ansible.builtin.systemd:
    name: "uptime-kuma"
    enabled: true
    state: started
    daemon_reload: true
